[target.wasm32-wasi]
rustflags = ["-C", "debuginfo=2"]
runner = "viceroy run -C fastly.toml -- "

[build]
target = "wasm32-wasi"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[env]
RUST_LOG = "info"
